### DIMENSIONES DE LAS VENTANAS ###
ANCHO_VENTANA = 800
ALTO_VENTANA = 600
DIMENSION_VENTANA = (ANCHO_VENTANA, ALTO_VENTANA)

### TITULOS DE LAS VENTANAS ###
TITULO_JUEGO = "Sudoku Clásico"
TITULO_PUNTAJE = "Puntajes"
TITULO_MENU = "Sudoku Clásico - Menú"

### COLORES ###
BLANCO = (255, 255, 255)
NEGRO = (0, 0, 0)
AZUL = (0, 122, 255)
GRIS_CLARO = (100, 100, 100)
AZUL_CLARO = (173, 216, 230)
COLOR_CELDA_ERRONEA = (255, 0, 0) # Rojo  (RGBA)
COLOR_CELDA_SELECCIONADA = (173, 216, 230, 128)   # Azul transparente (RGBA)


### IMAGENES ###
FONDO_MENU_PRINCIPAL = "imagenes/menu_principal.png"
LETRA_MENU_PRINCIPAL = "imagenes/fuente.ttf"
CAPTION = "imagenes/sudoku-caption.webp"

### TABLERO ###
ANCHO_CELDA_TABLERO = 50
ALTO_CELDA_TABLERO = 50
INICIO_X_TABLERO = 10
INICIO_Y_TABLERO = 70
GROSOR_LINEA = 1
GROSOR_LINEA_GRUESA = 4
GROSOR_NUMEROS = 25

### TABLA OPCIONES ###
### VARIABLES TABLA OPCIONES NUMERICAS ###
ANCHO_CELDA_OPCIONES = 80
ALTO_CELDA_OPCIONES = 50
INICIO_Y_OPCIONES = 500
INICIO_Y_OPCIONES = 70
GROSOR_LINEAS_OPCIONES = 2

NUMEROS_SUDOKU = [1, 2, 3, 4, 5, 6, 7, 8, 9]

