### DIMENSIONES DE LAS VENTANAS ###
ANCHO_VENTANA = 800
ALTO_VENTANA = 600
DIMENSION_VENTANA = (ANCHO_VENTANA, ALTO_VENTANA)

### TITULOS DE LAS VENTANAS ###
TITULO_JUEGO = "Sudoku Clásico"
TITULO_PUNTAJE = "Puntajes"
TITULO_MENU = "Sudoku Clásico - Menú"

### COLORES ###
BLANCO = (255, 255, 255)
NEGRO = (0, 0, 0)
AZUL = (0, 122, 255)
GRIS_CLARO = (100, 100, 100)
AZUL_CLARO = (173, 216, 230)

### IMAGENES ###
FONDO_MENU_PRINCIPAL = "imagenes/menu_principal.png"
LETRA_MENU_PRINCIPAL = "imagenes/fuente.ttf"
CAPTION = "imagenes/sudoku-caption.webp"

